Repository Final-Project-Team6/BE_Project, pull requests merged in 2024-05, with the labels that each got.

#15 ⚙️SET: Common 디렉토리를 Global 디렉토리로 이동하기
  aptner/src/main/java/com/fastcampus/aptner/global/common/BaseTimeEntity.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
Labels: enhancement

#17 ✨ENH: 인증 성공과 실패 핸들러 작성하기
  aptner/build.gradle
  aptner/src/main/java/com/fastcampus/aptner/auth/config/CustomSecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/MemberDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/CustomUserDetailsService.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/handler/APILoginFailHandler.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/handler/APILoginSuccessHandler.java
  aptner/src/main/resources/application-test.yml
  aptner/src/test/java/com/fastcampus/aptner/member/repository/MemberRepositoryTest.java
Labels: enhancement

#23 Deploy 5/2
  .github/workflows/main.yml
  aptner/build.gradle
  aptner/src/main/java/com/fastcampus/aptner/AptnerApplication.java
  aptner/src/main/java/com/fastcampus/aptner/auth/config/CustomSecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/aws/AwsS3Controller.java
  aptner/src/main/java/com/fastcampus/aptner/aws/AwsS3Service.java
  aptner/src/main/java/com/fastcampus/aptner/global/common/BaseTimeEntity.java
  aptner/src/main/java/com/fastcampus/aptner/global/config/S3Config.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberRole.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/MemberDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/CustomUserDetailsService.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/handler/APILoginFailHandler.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/handler/APILoginSuccessHandler.java
  aptner/src/main/resources/application-local.yml
  aptner/src/main/resources/application-test.yml
  aptner/src/main/resources/application.properties
  aptner/src/main/resources/application.yml
  aptner/src/test/java/com/fastcampus/aptner/member/repository/MemberRepositoryTest.java
Labels: deploy

#25 🚑FIX : main.yml 수정
  .github/workflows/main.yml
Labels: bug

#26 ✨ENH : 회원 수정, 등록, 삭제 구현하기
  aptner/src/main/java/com/fastcampus/aptner/auth/config/CustomSecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/aop/CustomValidationAdvice.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/common/BaseTimeEntity.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/exception/DataDuplicateKeyException.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/exception/DataNotFoundException.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/exception/NotMatchPasswordException.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/exception/SamePasswordException.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberRole.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/MemberDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/request/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/request/UpdateMemberDetailsRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/request/UpdateMemberPasswordRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/response/DetailsMemberResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/response/HttpMemberResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/CustomUserDetailsService.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/handler/APILoginFailHandler.java
  aptner/src/main/java/com/fastcampus/aptner/member/security/handler/APILoginSuccessHandler.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/CryptPasswordService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/CryptPasswordServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/test/java/com/fastcampus/aptner/member/repository/MemberRepositoryTest.java
Labels: enhancement

#31 회원 엔티티 및 DTO 생성하기
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Subscription.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/SignUpMemberRequest.java
Labels: enhancement

#41 🔀MERG : Hotfix
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java
Labels: bug

#47 Deploy 5/14
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/error/VoteErrorCode.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/VoteController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Comment.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/CommentVote.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Vote.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/VoteType.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/CommentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/VoteRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: deploy

#50 ✨ENH : 민원 게시판 기능
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/dto/AnnouncementDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/enumType/OrderBy.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/enumType/OrderType.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/enumType/PostStatus.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/enumType/SearchType.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/domain/Complaint.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/domain/ComplaintCategory.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/domain/ComplaintStatus.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/domain/ComplaintType.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintCategoryRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/VoteController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/CommentType.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/VoteType.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/CommentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: documentation, enhancement

#56 예외 수정 및 회원, JWT 컨트롤러 이름 변경 및 분리하기
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/CreateApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/CreateApartmentService.java
  aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/CustomExceptionHandler.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/aop/CustomValidationAdvice.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/isLoginArgumentResolver.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberRole.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/HttpResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/loginMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/loginMemberServiceImpl.java
Labels: enhancement

#58 JWT + 스프링 시큐리티 이슈 수정 및 회원 리팩토링 및 스웨거 설명 추가하기
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/CreateApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/UpdateApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentResponse.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/repository/ApartmentRepository.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentService.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/UpdateApartmentService.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/UpdateApartmentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/aop/CustomValidationAdvice.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/filter/JwtAuthenticationFilter.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/provider/JwtAuthenticationProvider.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/token/JwtAuthenticationToken.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/JWTMemberInfoDTO.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/JwtTokenizer.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/MemberInfoRequest.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/isLoginArgumentResolver.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateNicknameRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/FindMemberRoleServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/loginMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java
Labels: enhancement

#60 아파트 이름으로 아파트 단 건 조회하기
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/UpdateApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentRequest.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentResponse.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#62 회원 API 수정 및 아파트, 회원 스웨거 변경하기
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/UpdateApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
Labels: enhancement

#65 리프레시 토큰 재발급 에러 발생 이슈 해결하기
  aptner/build.gradle
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/CustomExceptionHandler.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/domain/TokenStorage.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/dto/TokenStorageDto.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/filter/JwtAuthenticationFilter.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/repository/RefreshTokenRepository.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/service/RefreshTokenService.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/JwtTokenizer.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Subscription.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/response/LoginMemberResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
Labels: enhancement

#66 ♻️REF : 아파트 이름으로 단 건 조회 수정하기
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentRequest.java
Labels: enhancement

#67 5월 22일 배포
  aptner/build.gradle
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentRequest.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/CustomExceptionHandler.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/domain/TokenStorage.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/dto/TokenStorageDto.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/filter/JwtAuthenticationFilter.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/repository/RefreshTokenRepository.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/service/RefreshTokenService.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/JwtTokenizer.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Subscription.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/response/LoginMemberResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
Labels: enhancement

#70 ♻️REF : 로그인 DTO 수정하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java
Labels: enhancement

#71 ♻️REF : 회원 로그인 스웨거 수정하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java
Labels: enhancement

#72 Deploy 5/24
  aptner/src/main/java/com/fastcampus/aptner/global/error/CommonErrorCode.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/domain/Announcement.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/domain/AnnouncementCategory.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/dto/AnnouncementDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementCategoryRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/repository/AnnouncementRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCategoryService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/enumType/SearchType.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/error/PostErrorCode.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/domain/Complaint.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/domain/ComplaintCategory.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintCategoryRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryAdminService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/VoteController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Comment.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Vote.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/CommentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/VoteDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/VoteRepository.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: enhancement

#75 ✨ENH : 아파트 조회기능 개선 및 오류 코드 수정
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/domain/Apartment.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/CreateApartmentRequest.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentResponse.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/repository/ApartmentRepository.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/CreateApartmentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentService.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/error/PostErrorCode.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: enhancement

#76 Deploy 0524-2
  aptner/src/main/java/com/fastcampus/aptner/apartment/controller/FindApartmentController.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/domain/Apartment.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/CreateApartmentRequest.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/FindApartmentResponse.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/repository/ApartmentRepository.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/CreateApartmentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentService.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/service/FindApartmentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/AnnouncementServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/service/admin/AnnouncementCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/common/error/PostErrorCode.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonService.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryService.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/admin/ComplaintCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: deploy

#77 ✨ENH : 공감기능 수정 API
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/AnnouncementController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/VoteController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Vote.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: enhancement

#78 회원 관련된 코드 및 스웨거 리팩토링하기
  aptner/src/main/java/com/fastcampus/aptner/jwt/controller/RefreshTokenController.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/dto/RefreshTokenRequest.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/isLogin.java
  aptner/src/main/java/com/fastcampus/aptner/jwt/util/isLoginArgumentResolver.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/LoginMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java
Labels: enhancement

#79 ♻️REF : 불필요한 import 및 @Valid 추가하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LoginMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#83 ♻️REF : 스웨거 권한 설정하기
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java
Labels: enhancement

#84 스웨거 권한 설정하기
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java
Labels: enhancement

#85 ♻️REF : 스웨거 권한 설정하기
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#90 ✨ENH : security 에 맞춰 관리자 url 수정
  aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#91 Deploy 05/27
  aptner/src/main/java/com/fastcampus/aptner/global/config/SwaggerConfig.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/announcement/controller/admin/AnnouncementCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: deploy

#93 ✨ENH : 회원 수정에 연관된 기능 작성하기
  aptner/src/main/java/com/fastcampus/aptner/apartment/domain/Home.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/ApartmentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/HomeDTO.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/repository/HomeRepository.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/aop/CustomValidationAdvice.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/MemberHomeController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberHome.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberRole.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Subscription.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/MemberHomeDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/SubscriptionDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/InsertMemberHomeRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateAuthenticationStatusRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberRoleRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberStatusRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateNicknameRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdatePasswordRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdatePhoneRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepositoryCustom.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepositoryImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRoleRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/SubscriptionRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/MemberHomeService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/MemberHomeServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
Labels: enhancement

#94 Deploy 05/27
  aptner/src/main/java/com/fastcampus/aptner/apartment/domain/Home.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/ApartmentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/dto/HomeDTO.java
  aptner/src/main/java/com/fastcampus/aptner/apartment/repository/HomeRepository.java
  aptner/src/main/java/com/fastcampus/aptner/global/error/CommonErrorCode.java
  aptner/src/main/java/com/fastcampus/aptner/global/handler/aop/CustomValidationAdvice.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/LogoutMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/MemberHomeController.java
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberHome.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/MemberRole.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Subscription.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/MemberHomeDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/SubscriptionDTO.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/InsertMemberHomeRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateAuthenticationStatusRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberRoleRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberStatusRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateNicknameRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdatePasswordRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdatePhoneRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepositoryCustom.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberHomeRepositoryImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/MemberRoleRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/repository/SubscriptionRepository.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/MemberHomeService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/MemberHomeServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/service/ComplaintServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: enhancement

#95 경로에 따른 권한 설정 및 불필요한 필드 제거하기
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java
Labels: enhancement

#96 Deploy 05/28
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/WebConfig.java
Labels: enhancement

#99 불필요한 임포트 삭제 및 경로 설정하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/HttpResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#100 🚑FIX : 시큐리티 경로 설정 및 apartmentName -> apartmentId 으로 변경하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/HttpResponse.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/JoinMemberRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/JoinMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#101 🚑FIX : 회원 스웨거 수정하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/JoinMemberController.java
Labels: enhancement

#102 ♻️REF : 시큐리티 경로 수정하기
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: enhancement

#106 ✨ENH :회원 이미지 필드 추가 및 수정 추가하기
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberProfileRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
Labels: enhancement

#107 ✨ENH : 내 댓글 목록 보기 기능
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Comment.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/CommentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: enhancement

#109 Deploy 05/30
  aptner/src/main/java/com/fastcampus/aptner/member/controller/UpdateMemberController.java
  aptner/src/main/java/com/fastcampus/aptner/member/domain/Member.java
  aptner/src/main/java/com/fastcampus/aptner/member/dto/reqeust/UpdateMemberProfileRequest.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberService.java
  aptner/src/main/java/com/fastcampus/aptner/member/service/UpdateMemberServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationController.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/admin/CommunicationAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/admin/CommunicationCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/Communication.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/dto/CommunicationDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/repository/CommunicationRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationService.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/controller/ComplaintController.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/dto/ComplaintDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/complaint/repository/ComplaintRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/controller/InformationCategoryController.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/controller/InformationController.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/controller/admin/InformationAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/controller/admin/InformationCategoryAdminController.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/dto/InformationDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationCategoryServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationService.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/service/InformationServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/service/admin/InformationAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/information/service/admin/InformationCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/controller/CommentController.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/domain/Comment.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/dto/CommentDTO.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDsl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/repository/CommentRepositoryDslImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/CommentServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteService.java
  aptner/src/main/java/com/fastcampus/aptner/post/opinion/service/VoteServiceImpl.java
Labels: deploy

#114 Deploy 0530
  aptner/src/main/java/com/fastcampus/aptner/post/communication/controller/CommunicationController.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/domain/Communication.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationCommonServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/CommunicationServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/post/communication/service/admin/CommunicationCategoryAdminServiceImpl.java
  aptner/src/main/java/com/fastcampus/aptner/security/config/SecurityConfig.java
Labels: deploy
